#############################################################################
# Makefile for building: MG001
# Generated by qmake (2.01a) (Qt 4.5.0) on: Sun Oct 4 21:34:53 2009
# Project:  MG001.pro
# Template: app
# Command: /home/oivoodoo/qtsdk-2009.01/qt/bin/qmake -spec ../../../qtsdk-2009.01/qt/mkspecs/linux-g++ -unix -o Makefile MG001.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../../qtsdk-2009.01/qt/mkspecs/linux-g++ -I. -I../../../qtsdk-2009.01/qt/include/QtCore -I../../../qtsdk-2009.01/qt/include/QtGui -I../../../qtsdk-2009.01/qt/include/QtOpenGL -I../../../qtsdk-2009.01/qt/include/QtSvg -I../../../qtsdk-2009.01/qt/include -I/usr/X11R6/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/oivoodoo/qtsdk-2009.01/qt/lib
LIBS          = $(SUBLIBS)  -L/home/oivoodoo/qtsdk-2009.01/qt/lib -L/usr/X11R6/lib -lQtSvg -L/home/oivoodoo/qtsdk-2009.01/qt/lib -L/usr/X11R6/lib -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -lQtOpenGL -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -lQtGui -pthread -lfreetype -lgobject-2.0 -lSM -lICE -pthread -pthread -lXrender -lfontconfig -lXext -lX11 -lQtCore -lm -pthread -lgthread-2.0 -lrt -lglib-2.0 -ldl -lGLU -lGL -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/oivoodoo/qtsdk-2009.01/qt/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		glscene.cpp \
		animationscene.cpp \
		dosanimation.cpp \
		voodoographics.cpp \
		moonwalker.cpp \
		animationobject.cpp \
		animationcontainer.cpp \
		road.cpp \
		asteroid.cpp moc_mainwindow.cpp \
		moc_glscene.cpp
OBJECTS       = main.o \
		mainwindow.o \
		glscene.o \
		animationscene.o \
		dosanimation.o \
		voodoographics.o \
		moonwalker.o \
		animationobject.o \
		animationcontainer.o \
		road.o \
		asteroid.o \
		moc_mainwindow.o \
		moc_glscene.o
DIST          = ../../../qtsdk-2009.01/qt/mkspecs/common/g++.conf \
		../../../qtsdk-2009.01/qt/mkspecs/common/unix.conf \
		../../../qtsdk-2009.01/qt/mkspecs/common/linux.conf \
		../../../qtsdk-2009.01/qt/mkspecs/qconfig.pri \
		../../../qtsdk-2009.01/qt/mkspecs/features/qt_functions.prf \
		../../../qtsdk-2009.01/qt/mkspecs/features/qt_config.prf \
		../../../qtsdk-2009.01/qt/mkspecs/features/exclusive_builds.prf \
		../../../qtsdk-2009.01/qt/mkspecs/features/default_pre.prf \
		../../../qtsdk-2009.01/qt/mkspecs/features/release.prf \
		../../../qtsdk-2009.01/qt/mkspecs/features/default_post.prf \
		../../../qtsdk-2009.01/qt/mkspecs/features/warn_on.prf \
		../../../qtsdk-2009.01/qt/mkspecs/features/qt.prf \
		../../../qtsdk-2009.01/qt/mkspecs/features/unix/opengl.prf \
		../../../qtsdk-2009.01/qt/mkspecs/features/unix/thread.prf \
		../../../qtsdk-2009.01/qt/mkspecs/features/moc.prf \
		../../../qtsdk-2009.01/qt/mkspecs/features/resources.prf \
		../../../qtsdk-2009.01/qt/mkspecs/features/uic.prf \
		../../../qtsdk-2009.01/qt/mkspecs/features/yacc.prf \
		../../../qtsdk-2009.01/qt/mkspecs/features/lex.prf \
		MG001.pro
QMAKE_TARGET  = MG001
DESTDIR       = 
TARGET        = MG001

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: MG001.pro  ../../../qtsdk-2009.01/qt/mkspecs/linux-g++/qmake.conf ../../../qtsdk-2009.01/qt/mkspecs/common/g++.conf \
		../../../qtsdk-2009.01/qt/mkspecs/common/unix.conf \
		../../../qtsdk-2009.01/qt/mkspecs/common/linux.conf \
		../../../qtsdk-2009.01/qt/mkspecs/qconfig.pri \
		../../../qtsdk-2009.01/qt/mkspecs/features/qt_functions.prf \
		../../../qtsdk-2009.01/qt/mkspecs/features/qt_config.prf \
		../../../qtsdk-2009.01/qt/mkspecs/features/exclusive_builds.prf \
		../../../qtsdk-2009.01/qt/mkspecs/features/default_pre.prf \
		../../../qtsdk-2009.01/qt/mkspecs/features/release.prf \
		../../../qtsdk-2009.01/qt/mkspecs/features/default_post.prf \
		../../../qtsdk-2009.01/qt/mkspecs/features/warn_on.prf \
		../../../qtsdk-2009.01/qt/mkspecs/features/qt.prf \
		../../../qtsdk-2009.01/qt/mkspecs/features/unix/opengl.prf \
		../../../qtsdk-2009.01/qt/mkspecs/features/unix/thread.prf \
		../../../qtsdk-2009.01/qt/mkspecs/features/moc.prf \
		../../../qtsdk-2009.01/qt/mkspecs/features/resources.prf \
		../../../qtsdk-2009.01/qt/mkspecs/features/uic.prf \
		../../../qtsdk-2009.01/qt/mkspecs/features/yacc.prf \
		../../../qtsdk-2009.01/qt/mkspecs/features/lex.prf \
		/home/oivoodoo/qtsdk-2009.01/qt/lib/libQtSvg.prl \
		/home/oivoodoo/qtsdk-2009.01/qt/lib/libQtGui.prl \
		/home/oivoodoo/qtsdk-2009.01/qt/lib/libQtCore.prl \
		/home/oivoodoo/qtsdk-2009.01/qt/lib/libQtOpenGL.prl
	$(QMAKE) -spec ../../../qtsdk-2009.01/qt/mkspecs/linux-g++ -unix -o Makefile MG001.pro
../../../qtsdk-2009.01/qt/mkspecs/common/g++.conf:
../../../qtsdk-2009.01/qt/mkspecs/common/unix.conf:
../../../qtsdk-2009.01/qt/mkspecs/common/linux.conf:
../../../qtsdk-2009.01/qt/mkspecs/qconfig.pri:
../../../qtsdk-2009.01/qt/mkspecs/features/qt_functions.prf:
../../../qtsdk-2009.01/qt/mkspecs/features/qt_config.prf:
../../../qtsdk-2009.01/qt/mkspecs/features/exclusive_builds.prf:
../../../qtsdk-2009.01/qt/mkspecs/features/default_pre.prf:
../../../qtsdk-2009.01/qt/mkspecs/features/release.prf:
../../../qtsdk-2009.01/qt/mkspecs/features/default_post.prf:
../../../qtsdk-2009.01/qt/mkspecs/features/warn_on.prf:
../../../qtsdk-2009.01/qt/mkspecs/features/qt.prf:
../../../qtsdk-2009.01/qt/mkspecs/features/unix/opengl.prf:
../../../qtsdk-2009.01/qt/mkspecs/features/unix/thread.prf:
../../../qtsdk-2009.01/qt/mkspecs/features/moc.prf:
../../../qtsdk-2009.01/qt/mkspecs/features/resources.prf:
../../../qtsdk-2009.01/qt/mkspecs/features/uic.prf:
../../../qtsdk-2009.01/qt/mkspecs/features/yacc.prf:
../../../qtsdk-2009.01/qt/mkspecs/features/lex.prf:
/home/oivoodoo/qtsdk-2009.01/qt/lib/libQtSvg.prl:
/home/oivoodoo/qtsdk-2009.01/qt/lib/libQtGui.prl:
/home/oivoodoo/qtsdk-2009.01/qt/lib/libQtCore.prl:
/home/oivoodoo/qtsdk-2009.01/qt/lib/libQtOpenGL.prl:
qmake:  FORCE
	@$(QMAKE) -spec ../../../qtsdk-2009.01/qt/mkspecs/linux-g++ -unix -o Makefile MG001.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/MG0011.0.0 || $(MKDIR) .tmp/MG0011.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/MG0011.0.0/ && $(COPY_FILE) --parents mainwindow.h glscene.h animationscene.h dosanimation.h voodoographics.h moonwalker.h animationobject.h animationcontainer.h road.h asteroid.h .tmp/MG0011.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp glscene.cpp animationscene.cpp dosanimation.cpp voodoographics.cpp moonwalker.cpp animationobject.cpp animationcontainer.cpp road.cpp asteroid.cpp .tmp/MG0011.0.0/ && (cd `dirname .tmp/MG0011.0.0` && $(TAR) MG0011.0.0.tar MG0011.0.0 && $(COMPRESS) MG0011.0.0.tar) && $(MOVE) `dirname .tmp/MG0011.0.0`/MG0011.0.0.tar.gz . && $(DEL_FILE) -r .tmp/MG0011.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_glscene.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_glscene.cpp
moc_mainwindow.cpp: mainwindow.h
	/home/oivoodoo/qtsdk-2009.01/qt/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_glscene.cpp: animationscene.h \
		glscene.h
	/home/oivoodoo/qtsdk-2009.01/qt/bin/moc $(DEFINES) $(INCPATH) glscene.h -o moc_glscene.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		ui_mainwindow.h \
		glscene.h \
		animationscene.h \
		dosanimation.h \
		voodoographics.h \
		animationcontainer.h \
		animationobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

glscene.o: glscene.cpp glscene.h \
		animationscene.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o glscene.o glscene.cpp

animationscene.o: animationscene.cpp animationscene.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o animationscene.o animationscene.cpp

dosanimation.o: dosanimation.cpp dosanimation.h \
		animationscene.h \
		voodoographics.h \
		animationcontainer.h \
		animationobject.h \
		moonwalker.h \
		asteroid.h \
		road.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dosanimation.o dosanimation.cpp

voodoographics.o: voodoographics.cpp voodoographics.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o voodoographics.o voodoographics.cpp

moonwalker.o: moonwalker.cpp moonwalker.h \
		animationobject.h \
		voodoographics.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moonwalker.o moonwalker.cpp

animationobject.o: animationobject.cpp animationobject.h \
		voodoographics.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o animationobject.o animationobject.cpp

animationcontainer.o: animationcontainer.cpp animationcontainer.h \
		animationobject.h \
		voodoographics.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o animationcontainer.o animationcontainer.cpp

road.o: road.cpp road.h \
		animationobject.h \
		voodoographics.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o road.o road.cpp

asteroid.o: asteroid.cpp asteroid.h \
		animationobject.h \
		voodoographics.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o asteroid.o asteroid.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_glscene.o: moc_glscene.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_glscene.o moc_glscene.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

